version: '3.8'

services:
  managair-db:
    image: mysql:8.3.0
    restart: always
    env_file:
      - .env.local
      - .env
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    expose:
      - '3306'
    volumes:
      - ./db/:/root/db
      - ./scripts:/docker-entrypoint-initdb.d
